server:
  port: 8080
  
spring:
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
              allowedOrigins: "*"
              allowedMethods: "*"
              allowedHeaders: "*"
      routes:
      - id: tests
        uri: http://localhost:9002/
        predicates:
        - Path=/tests/**
      - id: testcenter
        uri: http://localhost:9001/
        predicates:
        - Path=/testcenter/**
  application:
    name: apigateway
    
         